Repository davep/textual-fspicker, pull requests merged in 2025-01, with the labels that each got.

#9 Add a drive selection widget, only on Windows
  textual_fspicker/base_dialog.py
  textual_fspicker/file_dialog.py
  textual_fspicker/parts/__init__.py
  textual_fspicker/parts/directory_navigation.py
  textual_fspicker/parts/drive_navigation.py
Labels: Enhancement

#13 v0.1.0
  ChangeLog.md
Labels: Housekeeping

#14 fix backward compatibility on windows
  src/textual_fspicker/parts/drive_navigation.py
Labels: Bug, Housekeeping

#15 Fix the way the directory label in `SelectDirectory` updates
  ChangeLog.md
  src/textual_fspicker/select_directory.py
Labels: Bug, Cosmetic

#16 v0.1.1
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#19 Drop support for Python 3.8
  .github/workflows/style-and-lint.yaml
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#20 General code tidying
  src/textual_fspicker/__main__.py
  src/textual_fspicker/base_dialog.py
  src/textual_fspicker/file_dialog.py
Labels: Housekeeping

#21 v0.2.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#22 Fix a docstring typo
  src/textual_fspicker/file_save.py
Labels: Documentation, Housekeeping
