Repository davep/textual-fspicker, pull requests merged in 2025-08, with the labels that each got.

#56 Import TypeAlias from typing_extensions
  ChangeLog.md
  pyproject.toml
  src/textual_fspicker/base_dialog.py
Labels: Bug

#57 Fix a typo in the ChangeLog
  ChangeLog.md
Labels: Documentation

#58 More older Python tweaks
  .github/workflows/style-and-lint.yaml
  ChangeLog.md
  pyproject.toml
  src/textual_fspicker/base_dialog.py
Labels: Bug

#61 Add a contribution guide
  CONTRIBUTING.md
Labels: Documentation, Housekeeping

#54 Add option to open directories on double click
  src/textual_fspicker/base_dialog.py
  src/textual_fspicker/file_dialog.py
  src/textual_fspicker/file_open.py
  src/textual_fspicker/parts/directory_navigation.py
  src/textual_fspicker/select_directory.py
Labels: Enhancement

#65 Tweak the way the docs are cleaned/built
  Makefile
Labels: Documentation, Housekeeping

#71 Switch from rye to uv for development management
  .github/workflows/style-and-lint.yaml
  ChangeLog.md
  Makefile
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  uv.lock
Labels: Housekeeping

#72 Add Python 3.14 as a tested/supported Python version
  .github/workflows/style-and-lint.yaml
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#74 Add a hook that allows controlling directory entry icons
  ChangeLog.md
  docs/source/library-contents/icons.md
  mkdocs.yml
  src/textual_fspicker/__init__.py
  src/textual_fspicker/icons.py
  src/textual_fspicker/parts/directory_navigation.py
Labels: Enhancement, TODO
